---
deployment:
  tasks:
    - cp /home/apogeeon/public_html/index.html /home/apogeeon/public_html_backup/index.html
    - cp -r /home/apogeeon/public_html/assets/. /home/apogeeon/public_html_backup/assets/
    - cp -r /home/apogeeon/repositories/motivate/dist/. /home/apogeeon/public_html/